michaelwestdev/creations/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import URL, DataRequired


class CreationForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    url = StringField("URL", validators=[DataRequired(), URL()])
    description = TextAreaField("Description", validators=[DataRequired()])
    submit = SubmitField("Post")

michaelwestdev/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

michaelwestdev/scripts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import URL, DataRequired


class ScriptForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    url = StringField("URL", validators=[DataRequired(), URL()])
    description = TextAreaField("Description", validators=[DataRequired()])
    submit = SubmitField("Post")

michaelwestdev/creations/__init__.py
# This __init__.py file tells the app this is the creations package

michaelwestdev/creations/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from michaelwestdev import db
from michaelwestdev.creations.forms import CreationForm
from michaelwestdev.models import Creation

creations = Blueprint("creations", __name__)


@creations.route("/creation/new", methods=["GET", "POST"])
@login_required
def new_creation():
    form = CreationForm()
    if form.validate_on_submit():
        creation = Creation(
            title=form.title.data,
            url=form.url.data,
            description=form.description.data,
            author=current_user,
        )
        db.session.add(creation)
        db.session.commit()
        flash("Your creation has been posted!", "success")
        return redirect(url_for("main.creations"))
    return render_template(
        "create_creation.html", title="New Creation", form=form, legend="New Creation"
    )


@creations.route("/creation/<int:creation_id>")
def creation(creation_id):
    creation = Creation.query.get_or_404(creation_id)
    return render_template("creation.html", title=creation.title, creation=creation)


@creations.route("/creation/<int:creation_id>/update", methods=["GET", "POST"])
@login_required
def update_creation(creation_id):
    creation = Creation.query.get_or_404(creation_id)
    if creation.author != current_user:
        abort(403)
    form = CreationForm()
    if form.validate_on_submit():
        creation.title = form.title.data
        creation.url = form.url.data
        creation.description = form.description.data
        db.session.commit()
        flash("Your creation has been updated!", "success")
        return redirect(url_for("creations.creation", creation_id=creation.id))
    elif request.method == "GET":
        form.title.data = creation.title
        form.url.data = creation.url
        form.description.data = creation.description
    return render_template(
        "create_creation.html",
        title="Update Creation",
        form=form,
        legend="Update Creation",
    )


@creations.route("/creation/<int:creation_id>/delete", methods=["POST"])
@login_required
def delete_creation(creation_id):
    creation = Creation.query.get_or_404(creation_id)
    if creation.author != current_user:
        abort(403)
    db.session.delete(creation)
    db.session.commit()
    flash("Your creation has been deleted!", "success")
    return redirect(url_for("main.creations"))

michaelwestdev/posts/__init__.py
# This __init__.py file tells the app this is the posts package

michaelwestdev/posts/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from michaelwestdev import db
from michaelwestdev.models import Post
from michaelwestdev.posts.forms import PostForm

posts = Blueprint("posts", __name__)


@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data, content=form.content.data, author=current_user
        )
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", "success")
        return redirect(url_for("main.posts"))
    return render_template(
        "create_post.html", title="New Post", form=form, legend="New Post"
    )


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("post.html", title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been updated!", "success")
        return redirect(url_for("posts.post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template(
        "create_post.html", title="Update Post", form=form, legend="Update Post"
    )


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", "success")
    return redirect(url_for("main.home"))

michaelwestdev/scripts/__init__.py
# This __init__.py file tells the app this is the creations package

michaelwestdev/scripts/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from michaelwestdev import db
from michaelwestdev.models import Script
from michaelwestdev.scripts.forms import ScriptForm

scripts = Blueprint("scripts", __name__)


@scripts.route("/script/new", methods=["GET", "POST"])
@login_required
def new_script():
    form = ScriptForm()
    if form.validate_on_submit():
        script = Script(
            title=form.title.data,
            url=form.url.data,
            description=form.description.data,
            author=current_user,
        )
        db.session.add(script)
        db.session.commit()
        flash("Your script has been posted!", "success")
        return redirect(url_for("main.scripts"))
    return render_template(
        "create_script.html", title="New script", form=form, legend="New Script"
    )


@scripts.route("/script/<int:script_id>")
def script(script_id):
    script = Script.query.get_or_404(script_id)
    return render_template("script.html", title=script.title, script=script)


@scripts.route("/script/<int:script_id>/update", methods=["GET", "POST"])
@login_required
def update_script(script_id):
    script = Script.query.get_or_404(script_id)
    if script.author != current_user:
        abort(403)
    form = ScriptForm()
    if form.validate_on_submit():
        script.title = form.title.data
        script.url = form.url.data
        script.description = form.description.data
        db.session.commit()
        flash("Your script has been updated!", "success")
        return redirect(url_for("scripts.script", script_id=script.id))
    elif request.method == "GET":
        form.title.data = script.title
        form.url.data = script.url
        form.description.data = script.description
    return render_template(
        "create_script.html", title="Update script", form=form, legend="Update script"
    )


@scripts.route("/script/<int:script_id>/delete", methods=["POST"])
@login_required
def delete_script(script_id):
    script = Script.query.get_or_404(script_id)
    if script.author != current_user:
        abort(403)
    db.session.delete(script)
    db.session.commit()
    flash("Your script has been deleted!", "success")
    return redirect(url_for("main.scripts"))

michaelwestdev/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

michaelwestdev/templates/create_creation.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.url.label(class="form-control-label") }}
                {% if form.url.errors %}
                    {{ form.url(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.url.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.url(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                    {{ form.description(class="form-control form-control-lg is-invalid", id="editor") }}
                    <div class="invalid-feedback">
                        {% for error in form.description.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.description(class="form-control form-control-lg", id="editor") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-dark") }}
        </div>
    </form>
</div>
{% endblock content %}
{% block scripts %}
    <script src="https://cdn.ckeditor.com/4.13.0/full/ckeditor.js"></script>
    <script src={{ url_for('static', filename='js/ckeditorconfig.js') }}></script>
{% endblock scripts %}

michaelwestdev/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid", id="editor") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg", id="editor") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-dark") }}
        </div>
    </form>
</div>
{% endblock content %}
{% block scripts %}
    <script src="https://cdn.ckeditor.com/4.13.0/full/ckeditor.js"></script>
    <script src={{ url_for('static', filename='js/ckeditorconfig.js') }}></script>
{% endblock scripts %}

michaelwestdev/templates/create_script.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.url.label(class="form-control-label") }}
                {% if form.url.errors %}
                    {{ form.url(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.url.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.url(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                    {{ form.description(class="form-control form-control-lg is-invalid", id="editor") }}
                    <div class="invalid-feedback">
                        {% for error in form.description.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.description(class="form-control form-control-lg", id="editor") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-dark") }}
        </div>
    </form>
</div>
{% endblock content %}
{% block scripts %}
    <script src="https://cdn.ckeditor.com/4.13.0/full/ckeditor.js"></script>
    <script src={{ url_for('static', filename='js/ckeditorconfig.js') }}></script>
{% endblock scripts %}

michaelwestdev/templates/creation.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section lead">
    <div class="media-body">
      <h1 class="article-title display-4 mt-2 text-center">{{ creation.title }}</h1>
      <p class="article-content">{{ creation.description | safe }}</p>
      <script src="{{ creation.url + '.js' }}"></script>
      {% if creation.author == current_user %}
        <div>
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('creations.update_creation', creation_id=creation.id) }}">Update</a>
          <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
      {% endif %}
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="deleteModalLabel">Delete Creation?</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <form action="{{ url_for('creations.delete_creation', creation_id=creation.id) }}" method="POST">
        <input class="btn btn-danger" type="submit" value="Delete">
      </form>
    </div>
  </div>
</div>
</div>
{% endblock content %}

michaelwestdev/templates/creations.html
{% extends "layout.html" %}
{% block styles %}
{% endblock styles %}
{% block content %}
    {% if creations %}
          <div class="col-md-12 well">
            <div class="pb-4 text-center">
                <h1 class="display-4">Creations</h1>
            </div>
            <div id="creations">
                <div class="flex-container-creations mb-3">
                {% for creation in creations.items %}
                    {% include "includes/_creation.html"%}
                {% endfor %}
                </div>
            </div>
          </div>
        {% include "includes/_creationspagination.html" %}
    {% endif %}
    {% include "includes/_getintouch.html" %}
{% endblock content %}
{% block scripts %}
{% endblock scripts %}

michaelwestdev/templates/home.html
{% extends "layout.html" %}
{% block content %}
{% include "includes/_intro.html" %}
{% include "includes/_activity.html" %}
{% include "includes/_getintouch.html" %}
{% endblock content %}

michaelwestdev/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='shortcut icon' type='image/x-icon' href="{{ url_for('static', filename='images/favicons/favicon.ico') }}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css?ver=4.7.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hack-font/3.003/web/hack.min.css">
    {% block styles %}{% endblock styles %}
    {% assets "css_main" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}"></link>
    {% endassets %}
    {% include "includes/_title.html" %}
</head>
<body>
    {% include "includes/_navbar.html" %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12">
                {% include "includes/_messages.html" %}
                {% block content %}{% endblock %}
            </div>
        </div>
        {% include "includes/_footer.html" %}
    </main>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    {% block scripts %}{% endblock %}
    {% assets "js_main" %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
</body>
</html>

michaelwestdev/templates/login.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="" class="form-login">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ legend }}</legend>
        <div class="form-group">
            {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid", placeholder="Email") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="form-control form-control-lg", placeholder="Email") }}
            {% endif %}
        </div>
        <div class="form-group">
            {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid", placeholder="Password") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.password(class="form-control form-control-lg", placeholder="Password") }}
            {% endif %}
        </div>
    </fieldset>
    <div class="form-group">
        {{ form.submit(class="btn btn-lg btn-dark btn-block") }}
    </div>
</form>
{% endblock content %}

michaelwestdev/templates/post.html
{% extends "layout.html" %}
{% block styles %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.9/styles/atom-one-dark.min.css">
{% endblock styles %}
{% block content %}
<article class="media content-section lead">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2">{{ post.author.username }}</a>
        <small class="text-muted lead">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
      </div>
      <h1 class="article-title display-4 mt-2">{{ post.title }}</h1>
      <p class="article-content">{{ post.content | safe }}</p>
      {% if post.author == current_user %}
        <div>
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
          <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
      {% endif %}
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
        <input class="btn btn-danger" type="submit" value="Delete">
      </form>
    </div>
  </div>
</div>
</div>
{% endblock content %}
{% block scripts %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.9/highlight.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/highlightinit.js') }}"></script>
{% endblock scripts %}

michaelwestdev/templates/posts.html
{% extends "layout.html" %}
{% block styles %}
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/hack-font@3/build/web/hack.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.9/styles/atom-one-dark.min.css">
{% endblock styles %}
{% block content %}
    {% if posts %}
            <div class="pb-4 text-center">
                <h1 class="display-4">Blog</h1>
            </div>
            <div id="posts">
                <div class="flex-container-posts mb-3">
                {% for post in posts.items %}
                    {% include "includes/_post.html"%}
                {% endfor %}
                </div>
            </div>
        {% include "includes/_postspagination.html" %}
    {% endif %}
    {% include "includes/_getintouch.html" %}
{% endblock content %}
{% block scripts %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.9/highlight.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/highlightinit.js') }}"></script>
{% endblock scripts %}

michaelwestdev/templates/resume.html
{% extends "layout.html" %}
{% block content %}
{% include "includes/_resume.html" %}
{% include "includes/_getintouch.html" %}
{% endblock content %}

michaelwestdev/templates/script.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section lead">
    <div class="media-body">
      <h1 class="article-title display-4 mt-2 text-center">{{ script.title }}</h1>
      <p class="article-content">{{ script.description | safe }}</p>
      <script src="{{ script.url + '.js' }}"></script>
      {% if script.author == current_user %}
        <div>
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('scripts.update_script', script_id=script.id) }}">Update</a>
          <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
      {% endif %}
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="deleteModalLabel">Delete script?</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <form action="{{ url_for('scripts.delete_script', script_id=script.id) }}" method="POST">
        <input class="btn btn-danger" type="submit" value="Delete">
      </form>
    </div>
  </div>
</div>
</div>
{% endblock content %}

michaelwestdev/templates/scripts.html
{% extends "layout.html" %}
{% block styles %}
{% endblock styles %}
{% block content %}
    {% if scripts %}
          <div class="col-md-12 well">
            <div class="pb-4 text-center">
                <h1 class="display-4">Scripts</h1>
            </div>
            <div id="scripts">
                <div class="flex-container-scripts mb-3">
                {% for script in scripts.items %}
                    {% include "includes/_script.html"%}
                {% endfor %}
                </div>
            </div>
          </div>
        {% include "includes/_scriptspagination.html" %}
    {% endif %}
    {% include "includes/_getintouch.html" %}
{% endblock content %}
{% block scripts %}
{% endblock scripts %}