michaelwestdev/creations/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import URL, DataRequired


class CreationForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    url = StringField("URL", validators=[DataRequired(), URL()])
    description = TextAreaField("Description", validators=[DataRequired()])
    submit = SubmitField("Post")

michaelwestdev/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

michaelwestdev/scripts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import URL, DataRequired


class ScriptForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    url = StringField("URL", validators=[DataRequired(), URL()])
    description = TextAreaField("Description", validators=[DataRequired()])
    submit = SubmitField("Post")

michaelwestdev/creations/__init__.py
# This __init__.py file tells the app this is the creations package

michaelwestdev/creations/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from michaelwestdev import db
from michaelwestdev.creations.forms import CreationForm
from michaelwestdev.models import Creation

creations = Blueprint("creations", __name__)


@creations.route("/creation/new", methods=["GET", "POST"])
@login_required
def new_creation():
    form = CreationForm()
    if form.validate_on_submit():
        creation = Creation(
            title=form.title.data,
            url=form.url.data,
            description=form.description.data,
            author=current_user,
        )
        db.session.add(creation)
        db.session.commit()
        flash("Your creation has been posted!", "success")
        return redirect(url_for("main.creations"))
    return render_template(
        "create_creation.html", title="New Creation", form=form, legend="New Creation"
    )


@creations.route("/creation/<int:creation_id>")
def creation(creation_id):
    creation = Creation.query.get_or_404(creation_id)
    return render_template("creation.html", title=creation.title, creation=creation)


@creations.route("/creation/<int:creation_id>/update", methods=["GET", "POST"])
@login_required
def update_creation(creation_id):
    creation = Creation.query.get_or_404(creation_id)
    if creation.author != current_user:
        abort(403)
    form = CreationForm()
    if form.validate_on_submit():
        creation.title = form.title.data
        creation.url = form.url.data
        creation.description = form.description.data
        db.session.commit()
        flash("Your creation has been updated!", "success")
        return redirect(url_for("creations.creation", creation_id=creation.id))
    elif request.method == "GET":
        form.title.data = creation.title
        form.url.data = creation.url
        form.description.data = creation.description
    return render_template(
        "create_creation.html",
        title="Update Creation",
        form=form,
        legend="Update Creation",
    )


@creations.route("/creation/<int:creation_id>/delete", methods=["POST"])
@login_required
def delete_creation(creation_id):
    creation = Creation.query.get_or_404(creation_id)
    if creation.author != current_user:
        abort(403)
    db.session.delete(creation)
    db.session.commit()
    flash("Your creation has been deleted!", "success")
    return redirect(url_for("main.creations"))

michaelwestdev/posts/__init__.py
# This __init__.py file tells the app this is the posts package

michaelwestdev/posts/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from michaelwestdev import db
from michaelwestdev.models import Post
from michaelwestdev.posts.forms import PostForm

posts = Blueprint("posts", __name__)


@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data, content=form.content.data, author=current_user
        )
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", "success")
        return redirect(url_for("main.posts"))
    return render_template(
        "create_post.html", title="New Post", form=form, legend="New Post"
    )


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("post.html", title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been updated!", "success")
        return redirect(url_for("posts.post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template(
        "create_post.html", title="Update Post", form=form, legend="Update Post"
    )


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", "success")
    return redirect(url_for("main.home"))

michaelwestdev/scripts/__init__.py
# This __init__.py file tells the app this is the creations package

michaelwestdev/scripts/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from michaelwestdev import db
from michaelwestdev.models import Script
from michaelwestdev.scripts.forms import ScriptForm

scripts = Blueprint("scripts", __name__)


@scripts.route("/script/new", methods=["GET", "POST"])
@login_required
def new_script():
    form = ScriptForm()
    if form.validate_on_submit():
        script = Script(
            title=form.title.data,
            url=form.url.data,
            description=form.description.data,
            author=current_user,
        )
        db.session.add(script)
        db.session.commit()
        flash("Your script has been posted!", "success")
        return redirect(url_for("main.scripts"))
    return render_template(
        "create_script.html", title="New script", form=form, legend="New Script"
    )


@scripts.route("/script/<int:script_id>")
def script(script_id):
    script = Script.query.get_or_404(script_id)
    return render_template("script.html", title=script.title, script=script)


@scripts.route("/script/<int:script_id>/update", methods=["GET", "POST"])
@login_required
def update_script(script_id):
    script = Script.query.get_or_404(script_id)
    if script.author != current_user:
        abort(403)
    form = ScriptForm()
    if form.validate_on_submit():
        script.title = form.title.data
        script.url = form.url.data
        script.description = form.description.data
        db.session.commit()
        flash("Your script has been updated!", "success")
        return redirect(url_for("scripts.script", script_id=script.id))
    elif request.method == "GET":
        form.title.data = script.title
        form.url.data = script.url
        form.description.data = script.description
    return render_template(
        "create_script.html", title="Update script", form=form, legend="Update script"
    )


@scripts.route("/script/<int:script_id>/delete", methods=["POST"])
@login_required
def delete_script(script_id):
    script = Script.query.get_or_404(script_id)
    if script.author != current_user:
        abort(403)
    db.session.delete(script)
    db.session.commit()
    flash("Your script has been deleted!", "success")
    return redirect(url_for("main.scripts"))

michaelwestdev/users/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from michaelwestdev import bcrypt, db, limiter
from michaelwestdev.models import User
from michaelwestdev.users.forms import LoginForm, UpdateAccountForm
from michaelwestdev.users.utils import save_picture

users = Blueprint("users", __name__)


@users.route("/login", methods=["GET", "POST"])
@limiter.limit("20/day;5/hour")
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login Unsuccessful. Please check email and password", "danger")
    return render_template("login.html", title="Login", form=form, legend="Sign in")


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        "static", filename="images/profile_pics/" + current_user.image_file
    )
    return render_template(
        "account.html", title="Account", image_file=image_file, form=form
    )

michaelwestdev/templates/includes/_activity.html
<div class="pricing-header pb-4 mx-auto text-center">
    <h1 class="display-4">Latest</h1>
</div>
<div class="flex-container-activity text-center mb-4">
    <div class="content-section mx-2 my-2">
        <h3 class="display-4"><a class="activity-title text-dark" href="{{ url_for('main.posts') }}">Posts <i class="fa fa-edit"></i></a></h3>
            <ul class="list-group">
                {% for latest_post in latest_posts %}
                <li class="list-group-item list-group-item-light"><a class="activity-item text-dark lead" href="{{ url_for('posts.post', post_id=latest_post.id) }}">{{ latest_post.title|truncate(35) }}</a></li>
                {% endfor %}
            </ul>
    </div>
    <div class="content-section mx-2 my-2">
        <h3 class="display-4"><a class="activity-title text-dark" href="{{ url_for('main.creations') }}">Creations <i class="fa fa-globe"></i></a></h3>
            <ul class="list-group">
                {% for latest_creation in latest_creations %}
                <li class="list-group-item list-group-item-light"><a class="activity-item text-dark lead" href="{{ url_for('creations.creation', creation_id=latest_creation.id) }}">{{ latest_creation.title|truncate(35) }}</a></li>
                {% endfor %}
            </ul>
    </div>
    <div class="content-section mx-2 my-2">
        <h3 class="display-4"><a class="activity-title text-dark" href="{{ url_for('main.scripts') }}">Scripts <i class="fa fa-code"></i></a></h3>
            <ul class="list-group">
                {% for latest_script in latest_scripts %}
                <li class="list-group-item list-group-item-light"><a class="activity-item text-dark lead" href="{{ url_for('scripts.script', script_id=latest_script.id) }}">{{ latest_script.title|truncate(35) }}</a></li>
                {% endfor %}
            </ul>
    </div>
</div>

michaelwestdev/templates/includes/_creation.html
<article class="media content-section mx-2 my-2 lead">
  <div class="media-body">
    <h1 class="display-4 text-center"><a class="article-title text-dark" href="{{ url_for('creations.creation', creation_id=creation.id) }}">{{ creation.title }}</a></h1>
    <p class="article-content">{{ creation.description | safe | truncate(100) }}</p>
  </div>
</article>

michaelwestdev/templates/includes/_creationspagination.html
{% if creations.pages > 1 %}
    <nav id="creations-pagination">
        <ul class="pagination justify-content-center">
            {% for page_num in creations.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if page_num %}
                {% if creations.page == page_num %}
                  <a class="btn btn-dark" href="{{ url_for('main.creations', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                  <a class="btn btn-outline-dark" href="{{ url_for('main.creations', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
              {% else %}
                ...
              {% endif %}
            {% endfor %}
        </ul>
    </nav>
{% endif %}

michaelwestdev/templates/includes/_footer.html
<footer class="page-footer font-small blue pt-4 border-top lead">
    <div class="footer-copyright text-center py-3">Powered by <a class="mr-1 text-dark footer-link" href="https://flask.palletsprojects.com/en/1.1.x/" target="_blank">Flask</a><i class="fa fa-flask"></i></div>
</footer>

michaelwestdev/templates/includes/_getintouch.html
<hr class="divider">
<div id="getintouch">
    <div class="px-3 py-3 mx-auto text-center">
        <h1 class="display-4">Get in Touch</h1>
        <p class="lead">Check out my code or contact me below</p>
    </div>
    <div class="mb-5 text-center flex-container flex-container-getintouch">
        <div class="raised mx-2 my-2">
            <div class="corner_top_left"></div>
            <div class="corner_bottom_right"></div>
            <div class="raised-item">
                <a href="https://gitlab.com/mwestdev" target="_blank"><i class="fa fa-gitlab fa-3x" alt="Gitlab"></i></a>
            </div>
        </div>
        <div class="raised mx-2 my-2">
            <div class="corner_top_left"></div>
            <div class="corner_bottom_right"></div>
            <div class="raised-item">
                <a href="https://www.linkedin.com/in/mwestdev" target="_blank"><i class="fa fa-linkedin fa-3x" alt="Linkedin"></i></a>
            </div>
        </div>
    </div>
</div>

michaelwestdev/templates/includes/_intro.html
<div class="pricing-header px-3 py-3 pt-md-4 pb-md-4 mx-auto text-center">
      <p class="lead">Hey 👋 , I'm a Front-End developer with a keen interest in leveraging Javascript, Python and APIs to create useful applications.</p>
</div>

michaelwestdev/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    <div class="alert-container lead">
      <div class="alert alert-{{ category }}">{{ message }}</div>
    </div>
    {% endfor %}
  {% endif %}
{% endwith %}

michaelwestdev/templates/includes/_navbar.html
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="/">Michael West</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link text-link" href="{{ url_for('main.posts') }}">Posts</a>
          <a class="nav-item nav-link text-link" href="{{ url_for('main.creations') }}">Creations</a>
          <a class="nav-item nav-link text-link" href="{{ url_for('main.scripts') }}">Scripts</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
            <li class="nav-item dropdown bg-steel">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    New
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ url_for('posts.new_post') }}">Post</a>
                    <a class="dropdown-item" href="{{ url_for('creations.new_creation') }}">Creation</a>
                    <a class="dropdown-item" href="{{ url_for('scripts.new_script') }}">Script</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img class="rounded-circle navbar-img" src="{{ url_for('static', filename='images/profile_pics/' + current_user.image_file) }}">
                </a>
                <div class="dropdown-menu" aria-labelledby="navbardropdown">
                    <a class="dropdown-item" href="{{ url_for('users.account') }}">Account</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a>
                </div>
            </li>
          {% else %}
            <a class="nav-item nav-link" href="https://gitlab.com/mwestdev" target="_blank"><i class="fa fa-gitlab mr-1 ml-1" alt="Gitlab"></i></a>
            <a class="nav-item nav-link" href="https://www.linkedin.com/in/mwestdev" target="_blank"><i class="fa fa-linkedin mr-1 ml-1" alt="Linkedin"></i></a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>

michaelwestdev/templates/includes/_post.html
<article class="media content-section mx-2 my-2 lead">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/profile_pics/' + post.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
            <p class="mr-2">{{ post.author.username }}</p>
          <small class="text-muted lead">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
        </div>
        <h1 class="display-4">
            <a class="article-title text-dark" href="{{ url_for('posts.post', post_id=post.id) }}">
            {{ post.title }}</h1>
            </a>
        </h1>
        <p class="article-content">{{ post.content | safe | truncate(100) | striptags | safe }}</p>
      </div>
</article>

michaelwestdev/templates/includes/_postspagination.html
{% if posts.pages > 1 %}
    <nav id="posts-pagination">
        <ul class="pagination justify-content-center">
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if page_num %}
                {% if posts.page == page_num %}
                  <a class="btn btn-dark" href="{{ url_for('main.posts', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                  <a class="btn btn-outline-dark" href="{{ url_for('main.posts', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
              {% else %}
                ...
              {% endif %}
            {% endfor %}
        </ul>
    </nav>
{% endif %}

michaelwestdev/templates/includes/_script.html
<article class="media content-section mx-2 my-2 lead">
  <div class="media-body">
    <h1 class="display-4 text-center"><a class="article-title text-dark" href="{{ url_for('scripts.script', script_id=script.id) }}">{{ script.title }}</a></h1>
    <p class="article-content">{{ script.description | safe | truncate(100) }}</p>
  </div>
</article>

michaelwestdev/templates/includes/_scriptspagination.html
{% if scripts.pages > 1 %}
    <nav id="scripts-pagination">
        <ul class="pagination justify-content-center">
            {% for page_num in scripts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if page_num %}
                {% if scripts.page == page_num %}
                  <a class="btn btn-dark" href="{{ url_for('main.scripts', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                  <a class="btn btn-outline-dark" href="{{ url_for('main.scripts', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
              {% else %}
                ...
              {% endif %}
            {% endfor %}
        </ul>
    </nav>
{% endif %}

michaelwestdev/templates/includes/_title.html
{% if title %}
    <title>Michael West - {{ title }}</title>
{% else %}
    <title>Michael West</title>
{% endif %}